import { GoogleGenAI, Type } from "@google/genai";
import type { AnalysisResult } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const analysisSchema = {
    type: Type.OBJECT,
    properties: {
        aiScore: {
            type: Type.NUMBER,
            description: "A percentage score from 0 to 100 indicating the likelihood of AI generation. 0 is definitely human, 100 is definitely AI.",
        },
        summary: {
            type: Type.STRING,
            description: "A brief one or two-sentence summary of the findings.",
        },
        perplexity: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of perplexity, e.g., 'Low', 'Medium', 'High'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the perplexity analysis, focusing on predictability of word choice." },
            },
            required: ['rating', 'analysis'],
        },
        burstiness: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of burstiness, e.g., 'Low', 'Medium', 'High'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the burstiness analysis, focusing on variation in sentence length and structure." },
            },
            required: ['rating', 'analysis'],
        },
        uniformity: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of uniformity, e.g., 'Consistent', 'Varied'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the uniformity analysis, focusing on consistent tone and style." },
            },
            required: ['rating', 'analysis'],
        },
    },
    required: ['aiScore', 'summary', 'perplexity', 'burstiness', 'uniformity'],
};

export const detectAIContent = async (text: string): Promise<AnalysisResult> => {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: `Analyze the following text for signs of AI generation. Be extremely critical. Look for:
1. **Predictable Patterns:** Consistent sentence structures, robotic syntax, and monotonous flow.
2. **Keyword Repetition & Low Perplexity:** Overuse of specific terms and predictable word choices.
3. **Mechanical Punctuation & Uniformity:** Unnatural punctuation and an overly consistent, sterile tone.
4. **Lack of Human Flair:** Absence of natural variation, personal voice, idioms, or subtle imperfections.
Based on this strict analysis, provide a detailed breakdown and a percentage score from 0-100 indicating the likelihood of AI generation. Text: "${text}"`,
            config: {
                systemInstruction: "You are a stringent, expert AI content analyst. Your primary goal is to identify text generated by large language models with a high degree of accuracy. Be critical in your assessment and assign a higher AI score if you find evidence of robotic patterns, even if the text is well-written.",
                responseMimeType: "application/json",
                responseSchema: analysisSchema,
            },
        });

        const jsonString = response.text.trim();
        const result = JSON.parse(jsonString) as AnalysisResult;
        return result;

    } catch (error) {
        console.error("Error detecting AI content:", error);
        throw new Error("Failed to analyze content. The model may have returned an invalid response.");
    }
};

export const humanizeText = async (text: string): Promise<string> => {
    try {
        const prompt = `You are a master of literary disguise. Your mission is to take robotic, AI-generated text and transform it into something so authentically human that it bypasses every AI detector on the planet. Think of yourself as a writer for The New Yorker who's been asked to rewrite a corporate memo to sound like a gripping, personal essay.

**Core Philosophy: Embrace Imperfection and Chaos.**
AI is predictable. Humans are not. Your rewrite must feel like it was written by a real person with unique quirks, a distinct voice, and a slightly chaotic thought process.

**The Humanization Matrix (Follow these rules without fail):**

1.  **Structural Anarchy:**
    *   **Sentence Whiplash:** Create extreme variations in sentence length. Juxtapose a three-word sentence with a 30-word one.
    *   **Paragraph Schizophrenia:** Obliterate the original paragraph structure. Some paragraphs should be a single, punchy sentence. Others can be long and meandering. No two consecutive paragraphs should feel similar in length or structure. This is the most critical rule.
    *   **Rebellious Openings:** Never start sentences with the same word or phrase back-to-back. Hunt down and destroy repetitive sentence starters.

2.  **Voice and Vernacular:**
    *   **Talk, Don't Write:** Use contractions liberally (it's, don't, you've). Write as if you're explaining the topic to a smart friend over coffee.
    *   **Inject Your Soul:** Use idioms, metaphors, and even a rhetorical question or two. Give the text a point of view. Example: Instead of "The data indicates a trend," try "So what's this data really telling us? It looks like..."
    *   **The AI Word Hitlist:** Eradicate these words and their ilk: utilize, leverage, delve into, a testament to, navigate, foster, underscore, intricate, multifaceted. Replace them with simple, direct language.
    *   **The Repetition Tax:** Pretend you have to pay a steep tax every time you repeat a non-essential word or phrase. This forces variety.

3.  **Punctuation Personality:**
    *   Go beyond periods and commas. Use em-dashes (—) for dramatic pauses or asides. Use semicolons (;) to connect related but independent thoughts. Use punctuation to create rhythm, not just to follow grammatical rules.

**Example Transformation:**
*   **AI Input:** "The primary objective of this initiative is the strategic implementation of data-driven methodologies to enhance consumer engagement. This approach facilitates a comprehensive understanding of market dynamics."
*   **Human Output:** "So, what's the big idea here? We're basically just using data to figure out what people actually *want*. Once you get that, connecting with them is the easy part. It's not rocket science."

**Final Command:**
*   Preserve the core meaning, facts, and data of the original text.
*   Do NOT include any preamble or post-amble. Your output must be ONLY the rewritten text.

Now, transform this text:

"${text}"`;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
              systemInstruction: "You are an expert copy editor. Your task is to rewrite AI-generated text to make it sound completely human, following a detailed set of instructions to the letter. Your output must be indistinguishable from a skilled human writer and bypass AI detectors.",
              temperature: 0.9,
              topP: 0.95,
              topK: 64,
            }
        });
        return response.text.trim();
    } catch (error) {
        console.error("Error rewriting text:", error);
        throw new Error("Failed to humanize content.");
    }
};