import { GoogleGenAI, Type } from "@google/genai";
import type { AnalysisResult } from '../types';

const analysisSchema = {
    type: Type.OBJECT,
    properties: {
        aiScore: {
            type: Type.NUMBER,
            description: "A percentage score from 0 to 100 indicating the likelihood of AI generation. 0 is definitely human, 100 is definitely AI.",
        },
        summary: {
            type: Type.STRING,
            description: "A brief one or two-sentence summary of the findings.",
        },
        perplexity: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of perplexity, e.g., 'Low', 'Medium', 'High'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the perplexity analysis, focusing on predictability of word choice." },
            },
            required: ['rating', 'analysis'],
        },
        burstiness: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of burstiness, e.g., 'Low', 'Medium', 'High'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the burstiness analysis, focusing on variation in sentence length and structure." },
            },
            required: ['rating', 'analysis'],
        },
        uniformity: {
            type: Type.OBJECT,
            properties: {
                rating: { type: Type.STRING, description: "A rating of uniformity, e.g., 'Consistent', 'Varied'." },
                analysis: { type: Type.STRING, description: "Detailed explanation of the uniformity analysis, focusing on consistent tone and style." },
            },
            required: ['rating', 'analysis'],
        },
    },
    required: ['aiScore', 'summary', 'perplexity', 'burstiness', 'uniformity'],
};

export const detectAIContent = async (apiKey: string, text: string): Promise<AnalysisResult> => {
    if (!apiKey) {
        throw new Error("Gemini API Key is missing.");
    }
    const ai = new GoogleGenAI({ apiKey });
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: `Analyze the following text for signs of AI generation. Be extremely critical. Look for:
1. **Predictable Patterns:** Consistent sentence structures, robotic syntax, and monotonous flow.
2. **Keyword Repetition & Low Perplexity:** Overuse of specific terms and predictable word choices.
3. **Mechanical Punctuation & Uniformity:** Unnatural punctuation and an overly consistent, sterile tone.
4. **Lack of Human Flair:** Absence of natural variation, personal voice, idioms, or subtle imperfections.
Based on this strict analysis, provide a detailed breakdown and a percentage score from 0-100 indicating the likelihood of AI generation. Text: "${text}"`,
            config: {
                systemInstruction: "You are a stringent, expert AI content analyst. Your primary goal is to identify text generated by large language models with a high degree of accuracy. Be critical in your assessment and assign a higher AI score if you find evidence of robotic patterns, even if the text is well-written.",
                responseMimeType: "application/json",
                responseSchema: analysisSchema,
            },
        });

        const jsonString = response.text.trim();
        const result = JSON.parse(jsonString) as AnalysisResult;
        return result;

    } catch (error) {
        console.error("Error detecting AI content:", error);
        throw new Error("Failed to analyze content. The model may have returned an invalid response or the API key may be invalid.");
    }
};

export const humanizeText = async (apiKey: string, text: string): Promise<string> => {
     if (!apiKey) {
        throw new Error("Gemini API Key is missing.");
    }
    const ai = new GoogleGenAI({ apiKey });
    try {
        const prompt = `You are an advanced AI humanizer bot. Your sole purpose is to rewrite AI-generated text to be completely indistinguishable from human writing. You must aggressively apply the following techniques to achieve this goal.

**1. Structural Variation (The Chaos Principle):**
- **Sentence Lengths:** Create jarring and unpredictable shifts in sentence length. Follow a very short sentence (3-5 words) with a much longer, complex one. Avoid rhythmic, medium-length sentences.
- **Paragraph Structure:** Decimate the original paragraph structure. Create some single-sentence paragraphs for emphasis. Merge other paragraphs. The structure must feel organic and not uniform.
- **Sentence Starters:** Actively hunt down and eliminate repetitive sentence starters. If two consecutive sentences start with a similar structure or word, rewrite one.

**2. Vocabulary & Phrasing (The Authenticity Engine):**
- **Ditch Formality:** Replace formal, academic words with simpler, more common alternatives. (e.g., 'utilize' -> 'use', 'facilitate' -> 'help', 'imperative' -> 'a must', 'a testament to' -> 'shows').
- **Use Contractions:** Liberally use contractions like "it's", "don't", "you've", "we're".
- **Inject Personality:** Add idioms, casual phrases, and rhetorical questions to give the text a voice. (e.g., "So, what's the bottom line?", "It's a no-brainer.").

**3. Punctuation & Flow (The Rhythm Section):**
- **Vary Punctuation:** Don't just use periods and commas. Use em-dashes (—) for asides or emphasis. Use semicolons (;) to link closely related ideas. The goal is to create a natural, spoken rhythm.

**Example of what to avoid (robotic input):**
"Economic reforms in Bangladesh during 2024 were a whirlwind of changes, largely sparked by a turbulent political climate. An interim government stepped in and immediately got down to business, aiming to steady the economy and get things back on a path of sustainable growth. Let's break down what happened, why it happened, and what kind of ripple effects we've seen so far."

**Example of desired human-like output:**
"2024 was a chaotic year for Bangladesh's economy, and politics was squarely to blame. An interim government had to jump in and start pulling levers, just trying to stop the bleeding and find some stability. So how'd we get here, and what did they actually do?"

**Your Task:**
Rewrite the following text. Do not add any commentary before or after. Your output must ONLY be the rewritten text.

Original Text:
"${text}"`;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
              systemInstruction: "You are an expert copy editor. Your task is to rewrite AI-generated text to make it sound completely human, following a detailed set of instructions to the letter. Your output must be indistinguishable from a skilled human writer and bypass AI detectors.",
              temperature: 0.9,
              topP: 0.95,
              topK: 64,
            }
        });
        return response.text.trim();
    } catch (error) {
        console.error("Error rewriting text:", error);
        throw new Error("Failed to humanize content. The model may have returned an invalid response or the API key may be invalid.");
    }
};
